<?php

namespace Discord\WebSockets;

class Event
{
	const READY 				= 'READY';
	const MESSAGE_CREATE 		= 'MESSAGE_CREATE';

	const GUILD_CREATE			= 'GUILD_CREATE';
	const GUILD_DELETE			= 'GUILD_DELETE';

	const CHANNEL_CREATE		= 'CHANNEL_CREATE';
	const CHANNEL_DELETE		= 'CHANNEL_DELETE';
	const CHANNEL_UPDATE		= 'CHANNEL_UPDATE';

	const GUILD_BAN_ADD			= 'GUILD_BAN_ADD';
	const GUILD_BAN_REMOVE		= 'GUILD_BAN_REMOVE';

	const GUILD_MEMBER_ADD		= 'GUILD_MEMBER_ADD';
	const GUILD_MEMBER_REMOVE	= 'GUILD_MEMBER_REMOVE';
}