name: Build Docs
on:
  push:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || contains(github.event.head_commit.message, 'build docs')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: iconv
          tools: composer
      - name: Install phpDocumentor
        run: >-
          composer create-project discord-php/phpdoc-tool:^1.0 phpdoc-tool
          --no-interaction --no-progress
          --repository='{"type":"vcs","url":"https://github.com/discord-php/phpdoc-tool"}'
      - name: Build class reference
        run: php phpdoc-tool/vendor/bin/phpdoc
      - name: Build documentation
        run: |
          cd ./docs
          yarn install
          yarn build
          sudo mv public/* ../build
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
