name: DiscordPHP Linting
run-name: ${{ github.actor }} is running linting
on:
  pull_request:
  push:
    branches: master

jobs:
  cs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP 8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
    - name: Install packages
      run: composer install --no-progress
    - name: Verify CS
      run: composer cs-verify
